### ISSUE TITLE
Navigating to a position can result in ending up several positions off the target. 

### ISSUE THREAD

**Issue by Bolling88** [readium/r2-navigator-kotlin#117]
For example, If I want to go to a position by calling the following code:
`val locator = publication.positionList[position]`
` go(locator, false, completion = {})`
I can potentially end up on a position more than 60 positions off the targeted position. 
Going to the last or first position always works, but different positions in the book seems to be drawn to specific positions. 
With this book for example:
[https://www.gutenberg.org/ebooks/61253.epub](url)
If I set the position to 700, I end up on position 680. But if I set the position to 680 directly, I will end up on the correct position, 680.

**Comment by benforsrup** [comment]
Any progress on this bug?

**Comment by mickael-menu** [comment]
I can't reproduce this issue in the test app. Could you provide more details following the new [Bug Report issue template](https://github.com/readium/r2-navigator-kotlin/issues/new?assignees=&labels=&template=bug_report.md&title=)? 

I tested with the book given by @Bolling88 and various positions including 680 and 700.

The test app doesn't have a scrollbar to select positions, so I created a new outline fragment to list the publication positions. I observe the `navigator.currentLocator` to receive the current position after jumping to an outline item.

You can try this patch (`git apply positions.patch.txt`) in `r2-testapp-kotlin`:
[positions.patch.txt](https://github.com/readium/r2-navigator-kotlin/files/6600540/positions.patch.txt)
