### ISSUE TITLE
Testapp sometimes crashes when navigating in the Hebrew sample book

### ISSUE THREAD

**Issue by qnga** [readium/r2-navigator-kotlin#133]
![Capture d’écran du 2020-05-22 14-11-40](https://user-images.githubusercontent.com/32197639/82666945-308e7c00-9c37-11ea-87e8-6badf33924dd.png) (in R2EpubActivity.kt)
`R2WebView.progression` is negative, so `positions[positionIndex]` raises an out of bounds exception and the app crashes.

**Comment by mickael-menu** [comment]
There might be something to fix in the JavaScript calculating the progression with RTL books.

But we also need to guard against crashes if the `positionIndex` is invalid, with `positions.indices.contains(positionIndex)`.
