### ISSUE TITLE
How to get initialized view instead of activity ?

### ISSUE THREAD

**Issue by MAVERlCK** [readium/r2-navigator-kotlin#139]
Hi,
Not sure if this is possible, but is that possible to retrieve a View (or ViewPager) object directly, instead of open a new screen activity ?
I wanted to integrate the reader into another view but I don't know if it is possible or not.

Thanks !

**Comment by mickael-menu** [comment]
Hi,

This is not possible at the moment, but [we plan to migrate to `Fragment` instead of `Activity`](https://github.com/readium/r2-navigator-kotlin/issues/115) in the short term.

**Comment by MAVERlCK** [comment]
Thanks for your help @mickael-menu , I'm gonna check this !

**Comment by MAVERlCK** [comment]
Fixed : fragments are working in latest alpha builds ! Thanks !
