### ISSUE TITLE
Evaluate replacing R2RTLViewPager and R2ViewPager with ViewPager2

### ISSUE THREAD

**Issue by stevenzeck** [readium/r2-navigator-kotlin#149]
I don't know the history of the usage of R2RTLViewPager, was it used just for RTL support?  ViewPager2 supports RTL natively.

Migration guide:  https://developer.android.com/training/animation/vp2-migration
Jetpack library reference:  https://developer.android.com/jetpack/androidx/releases/viewpager2
Class docs:  https://developer.android.com/reference/androidx/viewpager2/widget/ViewPager2

I had looked at this before but had personal things come up, so had to stop.  Once #148 is merged I can take another look.

**Comment by mickael-menu** [comment]
Thanks, such contribution is most welcome! And yes, as far as I know `R2RTLViewPager` was here for the RTL support.

Right now, I'm focused on releasing the `2.0.0-alpha.1`, but once this is behind us, I'll take a look at #148 first thing.

**Comment by stevenzeck** [comment]
Initial investigation

- ViewPager2` would eliminate the need for R2RTLViewPager and R2ViewPager
- `ViewPager2` is final so can't be extended
- `addOnPageChangeListener` is replaced by `registerOnPageChangeCallback`
- VIewPager2 has a `layoutDirection` attribute that accepts a `View.LAYOUT_DIRECTION_` int.  Thinking of adding these to the `ReadingProgression` enum class
- FragmentStatePagerAdapter is replaced by FragmentStateAdapter

I replaced all of these locally and am trying to get through errors and how best to replace some of the old ViewPager code (like setPrimaryItem)

**Comment by mickael-menu** [comment]
@stevenzeck This sounds great, thanks for taking a look into this.

> `VIewPager2` has a layoutDirection attribute that accepts a `View.LAYOUT_DIRECTION_` int. Thinking of adding these to the ReadingProgression enum class

For `ReadingProgression` [we're limited to what is specified](https://github.com/readium/webpub-manifest/blob/db2fc3d6d3d6c6d23d77b6039c0425dedd94f85b/schema/metadata.schema.json#L123-L131) in [RWPM](https://readium.org/webpub-manifest/), so: left to right, right to left, top to bottom, bottom to top and auto. So what do you need to add? I think that we won't use `LAYOUT_DIRECTION_INHERIT` and `LAYOUT_DIRECTION_LOCALE`.

**Comment by stevenzeck** [comment]
I was hesitant at first to put the logic that determines which one to use in [EpubNavigatorFragment](https://github.com/readium/r2-navigator-kotlin/blob/30d233b4abc8a23e36e08137c5b27f00be2c67a2/r2-navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt#L140).  But now I don't think it's horrible to just put it there.

I pushed a first round to the [testapp](https://github.com/stevenzeck/r2-testapp-kotlin/tree/viewpager2) and [navigator](https://github.com/stevenzeck/r2-navigator-kotlin/tree/viewpager2) repositories.  I definitely broke reading settings as it doesn't update CSS to the proper webview.  Possibly broke search as well as it just spins. I'm guessing the scroll modes are also broken.  But feel free to take a look and offer suggestions.
