### ISSUE TITLE
[EPUB FXL] Panning in a zoom resource is broken

### ISSUE THREAD

**Issue by mickael-menu** [readium/r2-navigator-kotlin#152]
When a FXL resource is zoomed in, there's no way to move around the viewport by panning it, it's blocked.

Related issue: When rotating the device to landscape, the EPUB FXL is zoomed and clipped (since we can't pan around).

**Comment by johanpoirier** [comment]
Hello, any idea why it is blocked? Or where the issue might be?

**Comment by mickael-menu** [comment]
Not really, I didn't look into this issue yet. My first guess would be that the `ViewPager`'s panning gesture is conflicting with the one from the `WebView`.

**Comment by johanpoirier** [comment]
Is the panning supposed to be handled on the Kotlin side or on the WebView/JS side?

**Comment by mickael-menu** [comment]
On the Kotlin side, by the `WebView`.

**Comment by johanpoirier** [comment]
Has it ever worked in the past? Reading the code, I have the feeling that it has never been implemented.

**Comment by mickael-menu** [comment]
Could be, I never saw it work.

**Comment by johanpoirier** [comment]
This [line](https://github.com/readium/r2-navigator-kotlin/blob/2.0.0-alpha.2/r2-navigator/src/main/java/org/readium/r2/navigator/epub/fxl/R2FXLLayout.kt#L461) is weird: 
```kotlin
private fun internalMove(posX: Float, posY: Float, clamp: Boolean): Boolean {
     return internalMoveBy(posX - posX, posY - posY, clamp)
}
```

**Comment by johanpoirier** [comment]
And [this one](https://github.com/readium/r2-navigator-kotlin/blob/2.0.0-alpha.2/r2-navigator/src/main/java/org/readium/r2/navigator/epub/fxl/R2FXLLayout.kt#L451) too:

```kotlin
if (!NumberUtils.isEqual(posX, posX) || !NumberUtils.isEqual(posY, posY)) {
```
