### ISSUE TITLE
Crash on orientation change UninitializedPropertyAccessException: lateinit property webView has not been initialized

### ISSUE THREAD

**Issue by artem-mi** [readium/r2-navigator-kotlin#185]
Hello.
I use the version **2.0.0-alpha.2** of readium kotlin libs.
The stacktrace of the crash:

> 2020-12-10 00:15:19.071 3958-3958/org.readium.r2reader E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: org.readium.r2reader, PID: 3958
>     kotlin.UninitializedPropertyAccessException: lateinit property webView has not been initialized
>         at org.readium.r2.navigator.pager.R2EpubPageFragment.getWebView(R2EpubPageFragment.kt:42)
>         at org.readium.r2.navigator.epub.EpubNavigatorFragment$onCreateView$2.onPageSelected(EpubNavigatorFragment.kt:175)
>         at org.readium.r2.navigator.pager.R2RTLViewPager$ReversingOnPageChangeListener.onPageSelected(R2RTLViewPager.java:265)
>         at androidx.viewpager.widget.ViewPager.dispatchOnPageSelected(ViewPager.java:1947)
>         at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:665)
>         at androidx.viewpager.widget.ViewPager.setCurrentItemInternal(ViewPager.java:631)
>         at androidx.viewpager.widget.ViewPager.onRestoreInstanceState(ViewPager.java:1462)
>         at org.readium.r2.navigator.pager.R2RTLViewPager.onRestoreInstanceState(R2RTLViewPager.java:186)
>         at android.view.View.dispatchRestoreInstanceState(View.java:20743)
>         at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3986)
>         at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
>         at android.view.View.restoreHierarchyState(View.java:20721)
>         at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:636)
>         at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:2997)
>         at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2988)
>         at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:584)
>         at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:280)
>         at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
>         at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1636)
>         at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3112)
>         at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3056)
>         at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
>         at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:473)
>         at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
>         at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
>         at android.app.Activity.performStart(Activity.java:8024)
>         at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
>         at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
>         at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
>         at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:223)
>         at android.app.ActivityThread.main(ActivityThread.java:7656)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

To reproduce it is enough to open a publication, swipe to another page and rotate the device.
The crash constantly reproduces in **r2-testapp-kotlin** (I've downloaded project from develop branch several days ago, so I think it's up-to-date), similarly in my app where I derive my activity from **R2EpubActivity**.

**Comment by mickael-menu** [comment]
Hi @artem-mi, this should already be fixed in the `develop` branches of the R2 libraries. Could you check it out and report back in this issue? Thanks

**Comment by artem-mi** [comment]
@mickael-menu yes, you are right, the crash is fixed in latests sources. Less _lateinit_-s in codebase - more safe the program) Thank you very much, the quality of libraries grows steadily!
