### ISSUE TITLE
Text highlight position isnt working

### ISSUE THREAD

**Issue by mrifni** [readium/r2-navigator-kotlin#194]
I have highlighted the text `beware` but its highlighting something else below.
<img src="https://user-images.githubusercontent.com/1643992/108047914-47cf8e00-703e-11eb-9038-10a306d19f25.jpeg" width="200" />

**Comment by mrifni** [comment]
do you know on which release this bug will be addressed?

**Comment by mickael-menu** [comment]
I don't know. It's very unlikely that I work on this, so unless there's an external contribution I guess it won't be fixed any time soon. I will focus on the [`Navigator2`](https://github.com/readium/r2-testapp-kotlin/discussions/394) and the future highlights implementation in it.

**Comment by mrifni** [comment]
are you able to point me where is the problem ? I can try to fix it and contribute

**Comment by mickael-menu** [comment]
Sorry I'm not familiar with the current highlights implementation, but most of it should be in `highlight.js`

**Comment by mrifni** [comment]
I cant find `highlight.js` in test app, is it in some other projects ?

**Comment by mrifni** [comment]
If the team is focusing on [Navigator2](https://github.com/readium/r2-testapp-kotlin/discussions/394) and future highlights within it then I guess its not worth trying to fix this bug. Any idea on the timeline for the Navigator2 ?

**Comment by mickael-menu** [comment]
I can't give a precise timeline but personally I will need highlights this year.

**Comment by mrifni** [comment]
I am in a bit of a dilemma now, want to launch my app within a month but all my books highlights or notes doesnt work all having the same issue, and interestingly all the books have been converted from the calibre.

**Comment by mrifni** [comment]
I think I found the exact issue causing this problem. Its to do with the style `margin: 1em 0`, after removing highlights and notes started working.

**Comment by mrifni** [comment]
its not the case actually, even after removing `margin: 1em 0` on the stylesheet still some pages highlights arent positioned correctly and for some pages its positioned correctly, its weird and difficult to debug. Not sure how to fix it.

<img src="https://user-images.githubusercontent.com/1643992/110837173-d2e82080-8298-11eb-92d9-3ef19f1488e3.jpeg" width="200"/>

**Comment by tang85** [comment]
@mrifni

**Comment by tang85** [comment]
@mrifni

**Comment by tang85** [comment]
Did you fixed it? @mrifni . As mickael-menu said you can fix it in highlight.js.Check codes in the method "createHighlightDom".There was an attribute "yOffset".

**Comment by mrifni** [comment]
@tang85 do you have a link?

**Comment by tang85** [comment]
@mrifni [https://github.com/readium/r2-navigator-kotlin/blob/develop/r2-navigator/src/main/assets/readium/scripts/highlight.js](url)

**Comment by mrifni** [comment]
@tang85 link doesnt work for me, sorry. where was this discussion happened by @mickael-menu ?

**Comment by mrifni** [comment]
this is fixed on latest develop branch now. thank you

**Comment by mickael-menu** [comment]
@mrifni Did you switch to the decorator API? Because I didn't do any fix in the legacy highlighting code.

**Comment by mrifni** [comment]
I tested after you merged the decorator api PR to develop branch. It's working with the latest develop branch.
