### ISSUE TITLE
Bookmarks menu

### ISSUE THREAD

**Issue by IdMostapha** [readium/r2-navigator-kotlin#21]
@IdMostapha commented on [Fri Aug 03 2018](https://github.com/readium/r2-testapp-kotlin/issues/77)

- Add a Bookmark button to the publication layout
- Add a Bookmarks tab next to the Table of Content
- List all bookmarks of the actual publication
- Add a "Delete" option to a bookmark item

**Comment by aferditamuriqi** [comment]
Closed with https://github.com/readium/r2-navigator-kotlin/pull/22
