### ISSUE TITLE
EPUB parsed as HTML5 instead of XHTML

### ISSUE THREAD

**Issue by jerome65536** [readium/r2-navigator-kotlin#215]
## Bug Report

EPUB parsed as HTML5 instead of XHTML (on Android only).

### What happened?

EPUB parsed as HTML5. Printing `document.documentElement.innerHTML` from Javascript shows `<div /><p>text</p>` incorrectly transformed into `<div><p>text</p></div>` instead of `<div></div><p>text</p>`.

Also, pagination with horizontal-scrolling mode is broken on Android, but this might be an unrelated issue.

### Expected behavior

EPUB parsed as XHTML like on iOS.

### How to reproduce?

Happens with the ebook at https://lbs-next.nota.dk/merkur/opds2/publication/718305/

#### Readium versions

* `r2-shared-kotlin`:
* `r2-streamer-kotlin`:
* `r2-navigator-kotlin`: Unsure which version.

#### Development environment

* OS: macOS 10.15.7
* IDE: Android Studio, different versions

#### Testing device

* Android version: 11
* Model: Both on emulator and OnePlus 7T Pro
* Is it an emulator? Yes and No

**Comment by jerome65536** [comment]
Seems to only happen when loading from the link directly with a `LinkAsset`, not when loading from an .epub file with the same contents with a `FileAsset`.

```kt
import android.util.Log
import org.readium.r2.shared.fetcher.Fetcher
import org.readium.r2.shared.fetcher.HttpFetcher
import org.readium.r2.shared.publication.Publication
import org.readium.r2.shared.publication.asset.PublicationAsset
import org.readium.r2.shared.util.Try
import org.readium.r2.shared.util.http.DefaultHttpClient
import org.readium.r2.shared.util.mediatype.MediaType

private const val TAG = "LinkAsset"

class LinkAsset(override val name: String, private val mediaType: MediaType) : PublicationAsset {
  override suspend fun createFetcher(
    dependencies: PublicationAsset.Dependencies,
    credentials: String?
  ): Try<Fetcher, Publication.OpeningException> {
    Log.d(TAG, "createFetcher, name=$name, mediaType=$mediaType")
    return Try.success(HttpFetcher(DefaultHttpClient(), name))
  }

  override suspend fun mediaType(): MediaType = mediaType
}
```

**Comment by mickael-menu** [comment]
As @qnga [pointed in Slack](https://readium.slack.com/archives/C703MSTQU/p1628164637007000?thread_ts=1628157244.002300&cid=C703MSTQU), this is probably caused by `MediaType.HTML` and `MediaType.XHTML` being treated as aliases in the Sniffer: https://github.com/readium/r2-shared-kotlin/blob/e77e4ab0cea09be3f6fc787925c48e851e4f1fae/r2-shared/src/main/java/org/readium/r2/shared/util/mediatype/Sniffer.kt#L42
