### ISSUE TITLE
Javascript object added but never removed

### ISSUE THREAD

**Issue by ErikHellman** [readium/r2-navigator-kotlin#52]
Currently, the "Android" object is added to the JavaScript context in the fragments (https://github.com/readium/r2-navigator-kotlin/blob/develop/r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2EpubPageFragment.kt#L84), but they are never removed when the fragment goes away. This means that we're effectively leaking a reference.

Since the `WebView` class is extended, a better solution would be to let this view handle the adding and removing of this JavaScript object itself inside its own lifecycle (`onAttached`/`onDetached`).

**Comment by mickael-menu** [comment]
@ErikHellman Thanks that was a good tip. I also had to destroy web views explicitly to fix all memory leaks: https://github.com/readium/r2-navigator-kotlin/blob/611a9b0661fbf7c2393274ad1fe4f7341e19b45f/r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2EpubPageFragment.kt#L235-L241
