### ISSUE TITLE
EPUB3 Javascript button click and other touch events on Javascript form are completely disabled if rendition layout is reflowable (= Scroll mode is OFF in Settings)

### ISSUE THREAD

**Issue by sumahadevan** [readium/r2-navigator-kotlin#73]
Issue was seen on the following build.

Version and Device Details:
R2 Reader Android App version: 2.0.0
GitHub Tag: V2.0.0-beta.4
Android mobile devices: Moto G3 running Android 6.0.1, and also Nokia 6.1 Plus running Android 9.0.

In the Android version, in order to allow clicking of buttons and other inputs, the user has to go to Settings and turn Scroll mode ON in order for touch to work. This is due to the following piece of code in the navigator submodule file referenced below.

https://github.com/readium/r2-navigator-kotlin/blob/develop/r2-navigator/src/main/java/org/readium/r2/navigator/R2EpubActivity.kt

The relevant piece of code disables touch handling if the rendition layout is reflowable:

        override fun onPageSelected(position: Int) {
            if (publication.metadata.rendition.layout == RenditionLayout.Reflowable) {
                resourcePager.disableTouchEvents = true
            }

While handling dynamic Javascript along with Reflowable layouts is a practical issue, disabling ALL touch events is incorrect (I verified with another EPUB that hyperlinks dont work when scroll mode is off). Further, this is NOT consistent with iOS where touch (including buttons!) works even when the rendition layout is reflowable.

Issue was originally logged in the published app, referenced below.

https://github.com/readium/r2-testapp-kotlin/issues/188

**Comment by sumahadevan** [comment]
After looking at the navigator code on both iOS and Android, specifically for webviews, I have a better handle on what the desired requirement here is. On Android currently if rendition layout is reflowable then touch events are completely disabled, while for fixed layouts (rendition layout 'pre-paginated') they are enabled. However, on iOS, touch events are ENABLED in both cases. Instead on iOS, the difference is that "evaluateJavaScript" calls are not made in the reflowable document webview, while they are made in the fixed layout webview (details in files below). Thus touch is enabled in both cases (allowing for example hyperlinks), but executing Javascript that is part of the document (ePUB3) is done only for fixed layout documents. This is definitely preferable to completely disabling touch for reflowable layouts. The two iOS webviews are:

https://github.com/readium/r2-navigator-swift/blob/develop/r2-navigator-swift/EPUB/ReflowableDocumentWebView.swift

https://github.com/readium/r2-navigator-swift/blob/develop/r2-navigator-swift/EPUB/FixedDocumentWebView.swift

Another small but important point: rendition layout can be specified in the document itself, to begin with globally at the meta level (as I should have done in my button click sample but identifying it as fixed-layout!), but can also be specified individually at the spine level (i.e. some spine entries of an ePUB3 document can be reflowable and others can be fixed layout). I am assuming (and one can easily check) that overrides at the spine level are being honored by the navigator (on both iOS and Android).

**Comment by sumahadevan** [comment]
I cross-checked with the button-click-epub3.epub and what I said above regarding iOS turns out not to be factually correct: on iOS even if the rendition layout is reflowable (scroll mode is OFF), the Javascript within the ePUB3 works fine on button click (so Javascript code works even in rendition layout is reflowable). Of course, this is a simple case where the page layout is not really affected by executing the Javascript, and it may not always be desirable to allow this as has been done in the iOS version. But of course the other extreme of disabling all touch for reflowable documents as done in Android version is not appropriate either.

**Comment by aferditamuriqi** [comment]
@sumahadevan is this a duplicate? I see the same issue title twice with different content, can you please update and I'll review

**Comment by aferditamuriqi** [comment]
@sumahadevan disabling is done on purpose until it is properly implemented, touch handling is not yet implemented but will be once the navigator API has been refactored

**Comment by sumahadevan** [comment]
@aferditamuriqi the reason for the duplicate is that I logged the same issue for the r2-testapp-kotlin, but separately for the r2-navigator-kotlin submodule once I realized that the code that disables touch events when rendition layout is reflowable is actually in this submodule (so the fix would most likely be made here). You may close the one for the actual Android app itself if you wish, as the current issue is adequate to track the problem.

I understand the point you make about disabling it for reflowable layouts until the refactoring is done (I saw that refactoring had recently been done for the iOS version). Not being able to use reflowable layout does not pose an immediate problem for me, as I can always switch to pre-paginated layout (Scroll = ON).

Probably more important for me in the refactoring is the current lack of responsiveness to touch of interactive elements (recently fixed in the recent iOS refactoring by identifying a list of interactive elements and giving priority in touch/tapping to them, so that repeated presses are not required). This issue has been logged by me for Android only at the level of the testapp itself, as I don't specifically know that the issue is in the navigator (although that seems likely in terms of the general R2 Reader architecture, and the R2 Reader internal Javascript code should ideally be as common as possible).

https://github.com/readium/r2-testapp-kotlin/issues/203
