### ISSUE TITLE
Use interface ( or something like this) instead of R2EpubActivity instance

### ISSUE THREAD

**Issue by prsolucoes** [readium/r2-navigator-kotlin#79]
Hi,

Im trying use the "R2ViewPager" and "R2EpubPageFragment" but getting error that my activity is not instance of "R2EpubActivity".

Can you change it to an interface (https://kotlinlang.org/docs/reference/interfaces.html) and a listener instead of the activity?

Don't make sense projects change their activity to use a ViewPager.

https://github.com/readium/r2-navigator-kotlin/search?q=webView.activity+%3D+activity+as+R2EpubActivity&unscoped_q=webView.activity+%3D+activity+as+R2EpubActivity

Thanks.

**Comment by aferditamuriqi** [comment]
this has been changed a while ago to not depend on extending R2EpubActivity
