### ISSUE TITLE
Epub content is out of screen

### ISSUE THREAD

**Issue by prsolucoes** [readium/r2-navigator-kotlin#94]
Hi,

After pass some pages, the epub content is going out of screen:

MY EBOOK:

![image](https://user-images.githubusercontent.com/395096/60101996-35029a00-9733-11e9-931b-b69a15485346.png)

READIUM NATIVE EBOOK (Dead Souls):

![image](https://user-images.githubusercontent.com/395096/60102112-7430eb00-9733-11e9-85ee-487484d32e66.png)

This is not specific with an ebook, but with all ebooks.

Thanks.

**Comment by llemeurfr** [comment]
I see the same issue with e.g. "The Waste Land", after ~25 pages.

**Comment by llemeurfr** [comment]
And in "Children's Litterature", the internal hyperlinks don't point at the proper column ("page"). It may be well related to this issue (to be confirmed). 

Af if the number of pixels related to the column shift in reflow mode was not equal to the exact size of the column, the delta being 1 px

**Comment by aferditamuriqi** [comment]
fixed in https://github.com/readium/r2-navigator-kotlin/pull/105 and  https://github.com/readium/r2-navigator-kotlin/pull/107

the issue mentioned about "Children's Litterature" is a different issue and i reopened a new one for that https://github.com/readium/r2-navigator-kotlin/issues/109
