### ISSUE TITLE
WebView keep scroll up on every move  

### ISSUE THREAD

**Issue by asouqi** [readium/r2-navigator-kotlin#97]
**Issue**
when [mIsBeingDragged](https://github.com/readium/r2-navigator-kotlin/blob/1c1ba2d21ebcba2128195842845a1377383883ea/r2-navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt#L670) set to true, then in [MotionEvent.ACTION_UP](https://github.com/readium/r2-navigator-kotlin/blob/1c1ba2d21ebcba2128195842845a1377383883ea/r2-navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt#L681) scroll to the first page in the WebView. and when MotionEvent.ACTION_UP event detected on the next move will return to the first page because of value mIsBeingDragged still true.

**Proposed Fix**
the issue was not present in the older version and if you noticed [mIsBeingDragged](https://github.com/readium/r2-navigator-kotlin/blob/ad7df1ac58f1077d90b14ed75a9d445e2418122c/r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2WebView.kt#L730) set to false
so if we set value to false in [MotionEvent.ACTION_DOWN](https://github.com/readium/r2-navigator-kotlin/blob/1c1ba2d21ebcba2128195842845a1377383883ea/r2-navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt#L640) will solve issue

and the last thing should we [setCurrentItemInternal](https://github.com/readium/r2-navigator-kotlin/blob/1c1ba2d21ebcba2128195842845a1377383883ea/r2-navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt#L692) just if scroll mode off 
![KeepScrollingUpIssue](https://user-images.githubusercontent.com/45534101/68800265-6f2cf380-0662-11ea-8f3c-9f1623256f05.gif)

**Comment by Sought** [comment]
Fixed in the pending pr.
https://github.com/readium/r2-navigator-kotlin/pull/96

**Comment by asouqi** [comment]
@Sought should we set [mIsBeingDragged](https://github.com/readium/r2-navigator-kotlin/blob/1c1ba2d21ebcba2128195842845a1377383883ea/r2-navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt#L670) to true just in case scroll mode off, because this suddenly cause WebView to scroll to the first page in case scroll mode on, or this something normal

**Comment by Sought** [comment]
What do you mean by "scroll to the first page in case scroll mode on"?

If you mean that going to page 5/20 with scroll mode off and activating it makes you go back to the beginning of the current section for example, then I tried it on an Android API 23, and nothing special happened.

Tried it on an emulated Android API 28 and it worked too.

**Comment by asouqi** [comment]
what I mean scrolling to (0,0) position, and it occurs in when [mIsBeingDragged](https://github.com/readium/r2-navigator-kotlin/blob/1c1ba2d21ebcba2128195842845a1377383883ea/r2-navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt#L681) set to true

![scrollingUp](https://user-images.githubusercontent.com/45534101/69009302-c382ec80-095c-11ea-95bd-734f654d656f.gif)

**Comment by aferditamuriqi** [comment]
fixed in https://github.com/readium/r2-navigator-kotlin/commit/2afe90d
